stages:
  - build
  - test
  - examples
build_src:
  stage: build
  tags:
    - qt5
    - c++14
  script:
    - cd src && qmake && make clean && make

build_tests:
  stage: build
  tags:
    - qt5
    - c++14
  script:
    - cd tests && qmake && make clean && qmake && make

run_tests:
  allow_failure: true
  stage: test
  tags:
    - qt5
    - c++14
  script:
    - cd tests && make run_all


example_qt_webserver:
  allow_failure: true
  stage: examples
  tags:
    - qt5
  script:
    - g++ --version && cd examples/qt_webserver && qmake && make clean && make