stages:
  - build
  - test
  - examples
build_src:
  stage: build
  tags:
    - qt5
    - c++14
  script:
    - cd src && qmake && make clean && make

build_run_tests:
  stage: test
  tags:
    - qt5
    - c++14
  script:
    - cd tests && qmake "CONFIG+=debug" && make && make run_all


examples:
  allow_failure: true
  stage: examples
  tags:
    - qt5
    - c++14
  script:
    - examples && qmake && make clean && make